[package]
name = "voxelicous-entity"
description = "Entity system for the Voxelicous engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
voxelicous-core.workspace = true
hecs.workspace = true
glam.workspace = true
